config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'blogs#index'
  get 'blogs' => 'blogs#index'
  get 'blogs/new' => 'blogs#new'
  post 'blogs' => 'blogs#create'
  get   'blogs/:id/edit'  => 'blogs#edit'
  delete  'blogs/:id'  => 'blogs#destroy'
  patch   'blogs/:id'  => 'blogs#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    @blogs = Blog.new
  end

  def create
    Blog.create(text: blog_params[:text],user_id: current_user.id)
    redirect_to controller: :blogs, action: :index

  end

  def destroy
    blog = Blog.find(params[:id])
    blog.destroy if blog.user_id == current_user.id
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
      blog = Blog.find(params[:id])
      if blog.user_id == current_user.id
        blog.update(text: params[:text])
      end
  end

  private
  def blog_params
      params.require(:blog).permit(:text)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/create.html.erb
 <div class="contents row">
    <div class="success">
      <h3 class="black-text text-darken-2">
        投稿が完了しました。
      </h3>
      <a class="btn" href="/blogs">投稿一覧へ戻る</a>
    </div>
</div>

app/views/blogs/destroy.html.erb
 <div class="contents row">
    <div class="success">
      <h3 class="black-text text-darken-2">
        削除が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
</div>

app/views/blogs/edit.html.erb
<div class="contents row">
    <%= form_for @blog, :url => {:action => 'update'} do |f|%>
      <h3 class="black-text text-darken-2">
        編集する
      </h3>
      <textarea class="black-text text-darken-2" cols="30" name="text" placeholder="text" rows="10"><%= @blog.text %></textarea>
      <input class="black-text text-darken-2" type="submit" value="SENT">
    <% end %>
</div>

app/views/blogs/index.html.erb
<div class="contents row" >
  <% @blogs.each do |blog| %>
    <div class="card white">
    <p class="black-text text-darken-2"><%= blog.text %></p>
     <% if user_signed_in? && current_user.id == blog.user_id %>
        <div class="more">
          <ul class="more_list">
            <li class="waves-effect waves-light btn">
              <%= link_to '編集', "/blogs/#{blog.id}/edit", method: :get %>
            </li>
            <li class="waves-effect waves-light btn">
              <%= link_to '削除', "/blogs/#{blog.id}", method: :delete %>
            </li>
          </ul>
        </div>
      <% end %>
        <%= simple_format(blog.text) %>
      <span class="name">
        <a href="/users/<%= blog.user_id %>">
        </a>
      </span>
    </div>
  <% end %>
</div>

app/views/blogs/new.html.erb
<div class="contents row">
  <%= form_for @blogs,url: blogs_path do |f| %>
          <div style="margin: 8px 0">
            <li class="black-text text-darken-2"><%= f.text_area :text, style: 'width: 100%;height: 300px;' %></li>
          </div>
          <div class="row">
            <div class="col10 push1">
              <li class="black-text text-darken-2"><%= f.submit %></li>
            </div>
          </div>
  <% end %>
</div>

app/views/blogs/update.html.erb
<div class="contents row">
    <div class="success">
      <h3>
       <span class="black-text text-darken-2">更新が完了しました。</span>
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

     <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

  <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>

  </head>

  <body>
  <nav class="teal darken-1">
   <div class="nav-wrapper">
   <header class="header">
    <div class="header__bar row">
      <h1 class="grid-6"><a href="/" class="brand-logo">Blog</a></h1>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <div class="user_nav grid-6">
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          <li><a class="post" href="/blogs/new">投稿する</a></li>
        </div>
      <% else %>
        <div class="grid-6">
          <li><%= link_to "ログイン", new_user_session_path, class: 'post' %></li>
          <li><%= link_to "新規登録", new_user_registration_path, class: 'post' %></li>
        </div>
      <% end %>
    </div>
   </header>
    <%= yield %>
  </ul>
  </div>
  </nav>
  </body>
</html>